description = """Basic scene 1"""

[config]
world_texture.type = "gradient"
world_texture.start_color= "blue"
world_texture.end_color= "red"

[camera]
type = "perspective"
screen_center = [0, 5, -10]
look_at = [0, 0, 15]
width = 32
height = 18

[[light]]
type = "point"
description = "Global white light"
source = [50, 100, -50]
color = [0.8, 0.8, 0.8]

[[object]]
description = ""
type = "sphere"
center = [0, 0, 0]
radius = 5
texture.type = "plain"
texture.color = "blue"

[[object]]
description = ""
type = "infinite_plan"
center = [0, -5, 0]
normal =  [0, 1, 0]
texture.type = "plain"
texture.color = "white"