name: Build Raytracer

on: [push]

jobs:

  native:

    name: Native Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Install latest Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Install libsndio for Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libsndio-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose


  wasm:

    name: WASM Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Install latest Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Install wasm-pack
        run: cargo -v install wasm-pack
      - name: Build
        run: wasm-pack -v build raytracer
      - name: Run tests
        run: wasm-pack -v test --firefox --headless raytracer